# Generated by Django 6.0 on 2025-12-12 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="godownstock",
            name="location_name",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="shopstock",
            name="is_on_display",
        ),
        migrations.AddField(
            model_name="saleitem",
            name="is_loose_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="batch",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="volume_value",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="cost_price_snapshot",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="quantity_sold",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="shopstock",
            name="quantity_loose",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
