# Generated by Django 6.0 on 2025-12-12 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_batch_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="category_snapshot",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product_name_snapshot",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.batch",
            ),
        ),
    ]
