# Generated by Django 6.0 on 2025-12-16 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_customer_loan_sale_loan_loanpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Transport", "Transport"),
                            ("Wages", "Wages"),
                            ("Bills", "Bills (EB/Water)"),
                            ("Extra", "Extra"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
