# Generated by Django 6.0 on 2025-12-28 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="expiry_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date_time",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
