# Generated by Django 6.0 on 2026-04-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_batch_expiry_date_alter_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_count', models.IntegerField(default=0)),
                ('sales_snapshot', models.JSONField(default=list)),
                ('expenses_snapshot', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
